# Generated by Django 5.0.4 on 2024-04-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PORTFOLIO', '0003_category_alter_graphicdesign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desciption',
            field=models.TextField(default='desciption'),
        ),
    ]
