# Generated by Django 5.0.4 on 2024-04-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PORTFOLIO', '0005_rename_desciption_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphicdesign',
            options={},
        ),
    ]
